language: scala
sudo: required
dist: trusty

matrix:
  include:
  - stage: build
    env: CI_SCRIPT=ci/test.sh
    jdk: oraclejdk9

  - stage: build
    env: CI_SCRIPT=ci/test.sh
    jdk: oraclejdk8

  - stage: release
    env: CI_SCRIPT="ci/on-master.py ci/release.sh"
    jdk: oraclejdk9
  - stage: release
    env: CI_SCRIPT="ci/on-master.py ci/publish-docs.sh"
    jdk: oraclejdk8

script:
  - curl -L -o ~/bin/mill https://github.com/lihaoyi/mill/releases/download/0.4.1/0.4.1-4-158d11 && chmod +x ~/bin/mill
  - export PATH=~/bin/mill:$PATH
  - "$CI_SCRIPT"

cache:
  directories:
  - $HOME/.coursier
