language: scala
sudo: required
dist: trusty

matrix:
  include:
  - stage: build
    script: ci/test.sh
    jdk: oraclejdk9

  - stage: build
    script: ci/test.sh
    jdk: oraclejdk8

  - stage: release
    script: "ci/on-master.py ci/release-github.sh"
    jdk: oraclejdk9
  - stage: release
    script: "ci/on-master.py ci/release-sonatype.sh"
    jdk: oraclejdk9
  - stage: release
    script: "ci/on-master.py ci/publish-docs.sh"
    jdk: oraclejdk8

cache:
  directories:
  - $HOME/.coursier
